name: Scalable-Backtesting-Infrastructure-Plot
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Vectorbt
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          # python training/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "### Vecotorbt Plots" > report.md
          # cat train/results.txt >> report.md
          cml-publish images/vectorbt/fast_and_slow_plot.png --md >> report.md
          cml-send-comment report.md